### ISSUE TITLE
time out property

### ISSUE THREAD

**Issue by JordanWoods** [hmongouachon/mgGlitch#1]
Hi there, just wondering if you can add a property for the glitching to stop after a set period of time?

**Comment by hmongouachon** [comment]
Hi !

Sorry but i don't have time for the moment to update the plugin. But if you want the plugin to stop glitching after a period of time, you can use the destroy method with setTimeout like below

`setTimeout(function () {
     $( ".glitch-img" ).mgGlitch({ destroy : true});
 }, 3300);` 

where 3300 is the period of time in milliseconds.

Hope it helps

**Comment by JordanWoods** [comment]
Excellent, thank you.
