### ISSUE TITLE
text with glitch effect

### ISSUE THREAD

**Issue by Mexikaner9** [hmongouachon/mgGlitch#2]
how can I have a text with glitch effect???
please help me

**Comment by hmongouachon** [comment]
Hi !

This plugin does not work well with small elements like text. But if you increase the size of the text to 150px you will see the effect. So you have two solutions : 

1 - Check the unmin version of the plugin

**Comment by hmongouachon** [comment]
Hi !

This plugin does not work well with small elements like text. But if you increase the size of the text to 150px you will see the effect. So you have two solutions : 

1 - Modify the plugin : 

Check the unmin version of the plugin here : 
https://github.com/hmongouachon/mgGlitch/blob/master/src/mgGlitch.js

Change line 126 : 
var clipPos1 = getRandomInt(10, 1900);
var clipPos2 = 9999;
var clipPos3 = getRandomInt(10, 1300);

to
var clipPos1 = getRandomInt(5, 40);
var clipPos2 = 9999;
var clipPos3 = getRandomInt(5, 20);

If it does not work check this codepen demos : 
https://codepen.io/search/pens?q=glitch+text&limit=all&type=type-pens

Hope it help !

**Comment by Mexikaner9** [comment]
thank you very much for your help and this fantastic plugin!
