### ISSUE TITLE
In WordPress get "TypeError: $ is not a function" error

### ISSUE THREAD

**Issue by outofhouse** [hmongouachon/mgGlitch#4]
Hi - trying to use the glitch effect on an image in a WordPress site - newbie to JS (sorry!). 
I've created my own codepen view to test it works with my image: [https://codepen.io/outofhouse/details/oNjMjeX](https://codepen.io/outofhouse/details/oNjMjeX)
I have uploaded the files to my child theme folder and used a snippet plugin to add the scripts. 
I'm getting the error in FireFox Console that:
> TypeError: $ is not a function

You can see the page where the glitch image is here: [http://insoundmind.wpengine.com](http://insoundmind.wpengine.com)

The code added to the header is as follows:
`<script src="http://insoundmind.wpengine.com/wp-content/themes/insoundmind-engage-child/js/mgGlitch.js"></script>
<script src="http://insoundmind.wpengine.com/wp-content/themes/insoundmind-engage-child/js/mgGlitch.min.js"></script>
<script>
// https://github.com/hmongouachon/mgGlitch
$( function() {
		$( ".glitch-img" ).mgGlitch({
          // set 'true' to stop the plugin
				  destroy : false, 
          // set 'false' to stop glitching
          glitch: true, 
          // set 'false' to stop scaling
          scale: true, 
          // set 'false' to stop glitch blending
          blend : true, 
          // select blend mode type
          blendModeType : 'hue',
          // set min time for glitch 1 elem
          glitch1TimeMin : 200, 
          // set max time for glitch 1 elem
          glitch1TimeMax : 400,
          // set min time for glitch 2 elem
          glitch2TimeMin : 10, 
          // set max time for glitch 2 elem
          glitch2TimeMax : 100, 
		});
});
 </script>`

Any chance you can help me with this?

**Comment by hmongouachon** [comment]
Hi there,

TypeError: $ is not a function
> this is mostly due to the fact that jQuery is not loaded on your site.
Be sure to load jquery before the mgGlitch plugin.

Morover, you don't need to include the script twice :
http://insoundmind.wpengine.com/wp-content/themes/insoundmind-engage-child/js/mgGlitch.js
http://insoundmind.wpengine.com/wp-content/themes/insoundmind-engage-child/js/mgGlitch.min.js
> this one is the minified version

Good luck


Hadrien
Freelance web developer
http://hmongouachon.com
+33 6 23 80 89 96

**Comment by outofhouse** [comment]
Brilliant - thanks for the help. In the end I had to load the file using a php function. I then had to edit the start of the script to `jQuery(document).ready(function($) {` 
Anyway - everything working now so thanks...
